CREATE DATABASE TEST2;
USE TEST2;

CREATE TABLE USER_ACCOUNT(
	USER_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    USER_EMAIL VARCHAR(100) DEFAULT NULL,
    USER_PSW VARCHAR(100) DEFAULT NULL,
	UNIQUE KEY my_uniq_id (USER_EMAIL,USER_PSW)
);

CREATE TABLE CONTACT(
	CONTACT_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CONTACT_NAME VARCHAR(100) NOT NULL,
    CONTACT_EMAIL VARCHAR(100) NOT NULL,
    CONTACT_NUMBER INT,
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT(USER_ID)

);

INSERT INTO USER_ACCOUNT (USER_EMAIL,USER_PSW) VALUES("john123@gmail.com","123");
SELECT * FROM USER_ACCOUNT;

INSERT INTO CONTACT (CONTACT_NAME,CONTACT_EMAIL,CONTACT_NUMBER,USER_ID) VALUES("Alex","Alex2@yahoo.com",123456789,1);
INSERT INTO CONTACT (CONTACT_NAME,CONTACT_EMAIL,CONTACT_NUMBER,USER_ID) VALUES("Mia","Mia2@yahoo.com",103456789,1);
SELECT * FROM CONTACT;





