CREATE DATABASE GRADEBOOK_TES7;
USE GRADEBOOK_TEST6;

CREATE TABLE TEACHER(
	TEACHER_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    EMAIL VARCHAR(100) DEFAULT NULL,
    PSW VARCHAR(100) DEFAULT NULL,
    FIRST_NAME  VARCHAR(100) DEFAULT NULL,	
    LAST_NAME  VARCHAR(100) DEFAULT NULL,
	UNIQUE KEY my_uniq_id (EMAIL,PSW)
);
CREATE TABLE STUDENT(
	STUDENT_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    EMAIL VARCHAR(100) DEFAULT NULL,
    PSW VARCHAR(100) DEFAULT NULL,
	FIRST_NAME  VARCHAR(100) DEFAULT NULL,	
    LAST_NAME  VARCHAR(100) DEFAULT NULL,
	UNIQUE KEY my_uniq_id (EMAIL,PSW)
    
);

CREATE TABLE CLASS(
	CLASS_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CLASS_NAME VARCHAR(100) DEFAULT NULL,
    HOMEWORK BOOLEAN,
    HOMEWORK_WEIGHT DOUBLE,
    PROJECT BOOLEAN,
    PROJECT_WEIGHT DOUBLE,
    TEST BOOLEAN,
    TEST_WEIGHT DOUBLE,
    LAB BOOLEAN,
    LAB_WEIGHT DOUBLE,
    PARTICIPATION BOOLEAN,
    PARTICIPATION_WEIGHT DOUBLE,
    TEACHER_ID INT,
    FOREIGN KEY (TEACHER_ID) REFERENCES TEACHER(TEACHER_ID)
);
CREATE TABLE STUDENT_GRADE(
	STUDENT_GRADE_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    GRADE DOUBLE,
    CLASS_ID INT,
    STUDENT_ID INT,
    FOREIGN KEY (CLASS_ID) REFERENCES CLASS(CLASS_ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)
);

CREATE TABLE CLASS_STUDENT(
	ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CLASS_ID INT,
    STUDENT_ID INT,
    FOREIGN KEY (CLASS_ID) REFERENCES CLASS(CLASS_ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)
);
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME, PSW, EMAIL) VALUES ("Mia", "", "123", "mia@gmail.com");
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME, PSW, EMAIL) VALUES ("Brad", "", "345", "brad@gmail.com");
INSERT INTO TEACHER (FIRST_NAME, LAST_NAME, PSW, EMAIL) VALUES ("Alex", "", "234", "alex@gmail.com");

INSERT INTO CLASS(CLASS_NAME, HOMEWORK, HOMEWORK_WEIGHT, TEST, TEST_WEIGHT, LAB, LAB_WEIGHT, PROJECT, PROJECT_WEIGHT, PARTICIPATION, PARTICIPATION_WEIGHT, TEACHER_ID)
			VALUES("MATH3344", true, 0.3, true, 0.3, false, 0.0, false, 0.0, true, 0.4, 1);
INSERT INTO STUDENT_GRADE (GRADE, CLASS_ID, STUDENT_ID) VALUES (90.5, 1, 1);
INSERT INTO STUDENT_GRADE (GRADE, CLASS_ID, STUDENT_ID) VALUES (95.5, 1, 2);

SELECT * FROM TEACHER;
SELECT * FROM CLASS;
SELECT * FROM STUDENT;
SELECT * FROM STUDENT_GRADE;
DROP DATABASE GRADE_BOOK_TEST6;
